### ISSUE TITLE
Zip Slip vulnerability

### ISSUE THREAD

**Issue by xcorail** [flubu-core/flubu.core#179]
Hi there

[LGTM](lgtm.com) discovered a potential occurrence of the Zip Slip vulnerability. The alert is available [here](https://lgtm.com/projects/g/flubu-core/flubu.core/snapshot/9e17889920c31aebf1b5b5885a533bdb072589f4/files/FlubuCore/Tasks/Packaging/UnzipTask.cs?sort=name&dir=ASC&mode=heatmap&showExcluded=true#x25fb49c5831978a3:1)

For more details about this vulnerability : https://lgtm.com/rules/1506511188430/
Best regards

**Comment by mzorec** [comment]
Thank you for rising an issue. Bug will be fixed asap.

**Comment by sjvs** [comment]
Glad to see that the LGTM.com alerts were of use, and that this vulnerability has now been fixed (in [7149177fd6cb4779679b789a1902e724cfd08307](https://github.com/flubu-core/flubu.core/commit/7149177fd6cb4779679b789a1902e724cfd08307)).

There are a few other alerts on LGTM.com that may be of interest: https://lgtm.com/projects/g/flubu-core/flubu.core/alerts

LGTM also offers automated code review for pull requests. It'll warn you about new vulnerabilities (like Zip Slip!) and other alerts before they're actually merged into `master`. Here's an example on how the AMPHTML project use it: https://github.com/ampproject/amphtml/pull/13060. You can enable it here: https://lgtm.com/projects/g/flubu-core/flubu.core/ci

(full disclosure: I'm one of @xcorail colleagues on the LGTM.com team)
