### ISSUE TITLE
Expose the output of ExternalProcessTaskBase

### ISSUE THREAD

**Issue by jenzy** [flubu-core/flubu.core#198]
The `ExternalProcessTaskBase` already captures the output of a program, however the properties `ProgramOutput` and `GetProgramOutput` are [protected](https://github.com/flubu-core/flubu.core/blob/1db678c1a63b6b3674011e5ac7356aecc357fa77/FlubuCore/Tasks/Process/ExternalProcessTaskBase.cs#L23). Is there any particular reason for this, or can I make these properties public (or add a public api similar to [RunProgramTask's](https://github.com/flubu-core/flubu.core/blob/1db678c1a63b6b3674011e5ac7356aecc357fa77/FlubuCore/Tasks/Process/IRunProgramTask.cs#L22)?

**Comment by mzorec** [comment]
You can make them public.

**Comment by jenzy** [comment]
Instead of just making them public I looked into making a more fluent API. However, methods `CaptureError` and `GetOutput` can't be added to `ExternalProcessTaskBase` as they already exist in the derived class `RunProgramTask`. I think the best course of action is to pull these methods (and `CaptureErrorOutput` and `GetErrorOutput` also) up into `ExternalProcessTaskBase` and make them virtual. An alternative is to add these "fluent" methods with different names (like `KeepProgramOutput()`, but I like consistency. Of course there is always the option of just making these properties public. What's your opinion?

**Comment by mzorec** [comment]
I look into it and I don't see that RunProgramTask would inherit from ExternalProcessTask. Were you looking at some other task maybe?

`    public class RunProgramTask : TaskBase<int, IRunProgramTask>, IRunProgramTask

But yes generally I agree with 

> . I think the best course of action is to pull these methods (and CaptureErrorOutput and GetErrorOutput also) up into ExternalProcessTaskBase and make them virtual.

**Comment by jenzy** [comment]
Sorry about that, looks like I got confused with the interfaces. `IRunProgramTask : IExternalProcess<IRunProgramTask>`. I'll make a PR.
