### ISSUE TITLE
Package task log always show when set loglevel is none 

### ISSUE THREAD

**Issue by jxnkwlp** [flubu-core/flubu.core#354]
**Describe the bug**
Package task log always show when set loglevel is none . 
code :
`  
context.CreateTarget("Zip")
            .SetDescription("Zip all modules.")
            .DependsOn("Publish")
            .AddTask(x => x
                    .PackageTask(PackOutputDir)
                    .AddDirectoryToPackage(OutputDir, "web", true)
                    .ZipPackage("web")
                    .WithLogLevel(LogLevel.None)); 
`

FlubuCore.Runner  version:  6.3.2

**Comment by jxnkwlp** [comment]
![20211212131911](https://user-images.githubusercontent.com/8208357/145701395-be2a9e31-297c-41a7-a518-b0a457fd94bf.png)

**Comment by mzorec** [comment]
For now you can use `DisableLogging` instead to disable logs on `PackageTask` .

`context.CreateTarget("Test").AddTask(x => x.PackageTask(RootDirectory).DisableLogging());`

In future version we will obsolete `DisableLogging` and fix `PackageTask` that it will work with `WithLogLevel`.

**Comment by mzorec** [comment]
Issue has been fixed.
