### ISSUE TITLE
CommonAssemblyInfo.cs analyzers

### ISSUE THREAD

**Issue by jenzy** [flubu-core/flubu.core#38]
CommonAssemblyInfo.cs should start with the `<auto-generated/>` header and not with the `using` directives. Otherwise analysers will still analyse the file. AFAIK analysers only check for the `<auto-generated />` tag in the leading trivia of the first token. 

Currently, StyleCopAnalyzers report [SA1512 A single-line comment within C# code is followed by a blank line](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1512.md) for the generated CommonAssemblyInfo.cs file.

**Comment by zoroz** [comment]
Fixed in version 2.1.2.0
