### ISSUE TITLE
Proposal: add debugging support

### ISSUE THREAD

**Issue by blazknuplez** [flubu-core/flubu.core#52]

**Comment by mzorec** [comment]
@blazknuplez  You can now test and debug build script through tests if needed.

https://github.com/flubu-core/examples/blob/master/NetCore_csproj/BuildScript/BuildScriptTests.cs

**Comment by mzorec** [comment]
Build script debuging by attaching to flubu process is now available.

https://github.com/flubu-core/flubu.core/wiki/6-Writing-build-script-tests,-debuging-and-running-flubu-tasks-in-other-applications
